services:
  mimic3:
    image: mycroftai/mimic3:latest
    volumes:
      - ./mimic3/:/home/mimic3/.local/share/mycroft/mimic3/voices/en_US/
    command: ["sh", "-c", "chmod 777 /home/mimic3/.local/share/mycroft/mimic3/"]
    ports:
      - '9090:59125'
